{% set name = "discord.py" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/discord.py-{{ version }}.tar.gz
  sha256: 027ccdd22b5bb66a9e19cbd8daa1bc74b49271a16a074d57e52f288fcfa208e8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - aiohttp >=3.6.0,<3.8.0
    - python >=3.5

test:
  imports:
    - discord
    - discord.ext.commands
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Rapptz/discord.py
  summary: A Python wrapper for the Discord API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - galaxyonfire
